### ISSUE TITLE
"TypeError: None cannot be in an index" w/ Plone 5 coredev (5012)

### ISSUE THREAD

**Issue by davilima6** [collective/webcouturier.dropdownmenu#16]
Steps to reproduce: install the product and open any page with global sections.

```
Traceback (most recent call last):
  File "/home/davi/Projetos/d11/mytheme/src/plone.app.viewletmanager/plone/app/viewletmanager/manager.py", line 110, in render
    html.append(viewlet.render())
  File "/home/davi/Projetos/d11/mytheme/src/plone.app.layout/plone/app/layout/viewlets/common.py", line 60, in render
    return self.index()
  File "/home/davi/Projetos/d11/mytheme/src/webcouturier.dropdownmenu/src/webcouturier/dropdownmenu/browser/dropdown.py", line 106, in index
    return self._template()
  File "/home/davi/Projetos/d11/mytheme/src/Zope2/src/Products/Five/browser/pagetemplatefile.py", line 125, in __call__
    return self.im_func(im_self, *args, **kw)
  File "/home/davi/Projetos/d11/mytheme/src/Zope2/src/Products/Five/browser/pagetemplatefile.py", line 59, in __call__
    sourceAnnotations=getattr(debug_flags, 'sourceAnnotations', 0),
  File "/home/davi/.buildout/eggs/zope.pagetemplate-3.6.3-py2.7.egg/zope/pagetemplate/pagetemplate.py", line 132, in pt_render
    strictinsert=0, sourceAnnotations=sourceAnnotations
  File "/home/davi/Projetos/d11/mytheme/src/five.pt/src/five/pt/engine.py", line 93, in __call__
    return self.template.render(**kwargs)
  File "/home/davi/.buildout/eggs/z3c.pt-3.0.0a1-py2.7.egg/z3c/pt/pagetemplate.py", line 163, in render
    return base_renderer(**context)
  File "/home/davi/.buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/zpt/template.py", line 258, in render
    return super(PageTemplate, self).render(**vars)
  File "/home/davi/.buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 191, in render
    raise_with_traceback(exc, tb)
  File "/home/davi/.buildout/eggs/Chameleon-2.22-py2.7.egg/chameleon/template.py", line 171, in render
    self._render(stream, econtext, rcontext)
  File "96d5423db290dd55a4a728f30649f414.py", line 293, in render
  File "/home/davi/Projetos/d11/mytheme/src/webcouturier.dropdownmenu/src/webcouturier/dropdownmenu/browser/dropdown.py", line 174, in getTabObject
    strategy = getMultiAdapter((tabObj, self.data), INavtreeStrategy)
  File "/home/davi/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 107, in getMultiAdapter
    adapter = queryMultiAdapter(objects, interface, name, context=context)
  File "/home/davi/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 120, in queryMultiAdapter
    return sitemanager.queryMultiAdapter(objects, interface, name, default)
  File "/home/davi/.buildout/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 238, in queryMultiAdapter
    objects, interface, name, default)
  File "/home/davi/.buildout/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 532, in queryMultiAdapter
    result = factory(*objects)
  File "/home/davi/Projetos/d11/mytheme/src/plone.app.portlets/plone/app/portlets/portlets/navigation.py", line 396, in __init__
    portlet.root_uid)
  File "/home/davi/Projetos/d11/mytheme/src/plone.app.portlets/plone/app/portlets/portlets/navigation.py", line 428, in getRootPath
    root = uuidToObject(root)
  File "/home/davi/Projetos/d11/mytheme/src/plone.app.uuid/plone/app/uuid/utils.py", line 31, in uuidToObject
    brain = uuidToCatalogBrain(uuid)
  File "/home/davi/Projetos/d11/mytheme/src/plone.app.uuid/plone/app/uuid/utils.py", line 49, in uuidToCatalogBrain
    result = catalog(UID=uuid)
  File "/home/davi/Projetos/d11/mytheme/src/Products.CMFPlone/Products/CMFPlone/CatalogTool.py", line 384, in searchResults
    return ZCatalog.searchResults(self, REQUEST, **kw)
  File "/home/davi/Projetos/d11/mytheme/src/Products.ZCatalog/src/Products/ZCatalog/ZCatalog.py", line 604, in searchResults
    return self._catalog.searchResults(REQUEST, used, **kw)
  File "/home/davi/Projetos/d11/mytheme/src/Products.ZCatalog/src/Products/ZCatalog/Catalog.py", line 1072, in searchResults
    return self.search(args, sort_indexes, reverse, sort_limit, _merge)
  File "/home/davi/Projetos/d11/mytheme/src/Products.ZCatalog/src/Products/ZCatalog/Catalog.py", line 549, in search
    r = _apply_index(query, rs)
  File "/home/davi/Projetos/d11/mytheme/src/Products.ZCatalog/src/Products/PluginIndexes/common/UnIndex.py", line 433, in _apply_index
    raise TypeError('None cannot be in an index.')
TypeError: None cannot be in an index.

 - Expression: "python:view.getTabObject(tabUrl = tab['url'], tabPath = tab.get('path'))"
 - Filename:   ... c/webcouturier/dropdownmenu/browser/dropdown_sections.pt
 - Location:   (line 27: col 38)
 - Source:     ... python:view.getTabObject(tabUrl = tab['url'], tabPath = tab.get('path')) ...
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               tab: {...} (4)
               views: <ViewMapper - at 0x7f3aa7d9db10>
               modules: <instance - at 0x7f3ab3b019e0>
               args: <tuple - at 0x7f3abb627050>
               here: <ImplicitAcquisitionWrapper Plone2 at 0x7f3aadb77140>
               user: <ImplicitAcquisitionWrapper - at 0x7f3aad7fc500>
               selected_tab: index_html
               nothing: <NoneType - at 0x91a870>
               template: <ViewPageTemplateFile - at 0x7f3aa7d9d8d0>
               container: <ImplicitAcquisitionWrapper Plone2 at 0x7f3aadb77140>
               portal_tabs: <list - at 0x7f3aad234440>
               request: <instance - at 0x7f3aad5392d8>
               wrapped_repeat: <SafeMapping - at 0x7f3aad332368>
               traverse_subpath: <list - at 0x7f3aa7fbb488>
               default: <object - at 0x7f3abb545500>
               loop: {...} (1)
               context: <ImplicitAcquisitionWrapper Plone2 at 0x7f3aadb77140>
               view: <DropdownMenuViewlet plone.global_sections at 0x7f3aa7b1ead0>
               tid: about-1
               translate: <function translate at 0x7f3aa7af7b90>
               root: <ImplicitAcquisitionWrapper Zope at 0x7f3aadd6c780>
               options: {...} (0)
               target_language: <NoneType - at 0x91a870>


> /home/davi/.buildout/eggs/Products.PDBDebugMode-1.3.1-py2.7.egg/Products/PDBDebugMode/pdblogging.py(54)error()
-> return result
(Pdb) c
```

**Comment by davilima6** [comment]
Might be related to:

    KeyError: 'Missing or empty <value key="csscompilation" /> in plone.bundles/webcouturier.dropdownmenu.'

Full traceback:

```
$ bin/plone-compile-resources --bundle=mybundle

Running command: /home/davi/Projetos/d11/mytheme/bin/instance run /home/davi/Projetos/d11/mytheme/src/Products.CMFPlone/Products/CMFPlone/_scripts/_generate_gruntfile.py
Using site id: Plone
Traceback (most recent call last):
  File "/home/davi/Projetos/d11/mytheme/parts/instance/bin/interpreter", line 284, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/home/davi/Projetos/d11/mytheme/src/Products.CMFPlone/Products/CMFPlone/_scripts/_generate_gruntfile.py", line 380, in <module>
    'in {}'.format(bundle.__prefix__))
KeyError: 'Missing or empty <value key="csscompilation" /> in plone.bundles/webcouturier.dropdownmenu.'
Traceback (most recent call last):
  File "bin/plone-compile-resources", line 274, in <module>
    sys.exit(Products.CMFPlone._scripts.compile_resources.main())
  File "/home/davi/Projetos/d11/mytheme/src/Products.CMFPlone/Products/CMFPlone/_scripts/compile_resources.py", line 65, in main
    generate_gruntfile.main(args)
  File "/home/davi/Projetos/d11/mytheme/src/Products.CMFPlone/Products/CMFPlone/_scripts/generate_gruntfile.py", line 45, in main
    subprocess.check_call(cmd, env=os.environ)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/davi/Projetos/d11/mytheme/bin/instance', 'run', '/home/davi/Projetos/d11/mytheme/src/Products.CMFPlone/Products/CMFPlone/_scripts/_generate_gruntfile.py']' returned non-zero exit status 1
```

**Comment by jensens** [comment]
still valid?

**Comment by jensens** [comment]
i dont think so, works fine here - pls. reopen otherwise
