### ISSUE TITLE
plone-compile-resources won't run when Dropdown in policy's metadata.xml

### ISSUE THREAD

**Issue by davilima6** [collective/webcouturier.dropdownmenu#17]
Steps to reproduce:
- Download the package by adding it to your setup.py or buildout profile
- Add Dropdown as dependency in your policy package's metadata.xml
- Add a Plone 5.0 site and install your policy package
- Try to run `./bin/plone-compile-resources` from your policy root dir.

Traceback (most recent call last):
  File "/vagrant/buildout/zeoserver/parts/client1/bin/interpreter", line 269, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/home/vagrant/var/buildout-cache/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/_scripts/_generate_gruntfile.py", line 387, in <module>
    target_dir = '/'.join(bundle.jscompilation.split('/')[:-1])
AttributeError: 'NoneType' object has no attribute 'split'
Traceback (most recent call last):
  File "bin/plone-compile-resources", line 259, in <module>
    sys.exit(Products.CMFPlone._scripts.compile_resources.main())
  File "/home/vagrant/var/buildout-cache/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/_scripts/compile_resources.py", line 63, in main
    generate_gruntfile.main(args)
  File "/home/vagrant/var/buildout-cache/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/_scripts/generate_gruntfile.py", line 42, in main
    subprocess.check_call(cmd, env=os.environ)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/vagrant/buildout/zeoserver/bin/client1', 'run', '/home/vagrant/var/buildout-cache/eggs/Products.CMFPlone-5.0-py2.7.egg/Products/CMFPlone/_scripts/_generate_gruntfile.py']' returned non-zero exit status 1

**Comment by davilima6** [comment]
In Coredev the traceback looks like this: https://github.com/collective/webcouturier.dropdownmenu/issues/16#issuecomment-153767247

**Comment by fulv** [comment]
+1

**Comment by jensens** [comment]
just tried, works now - coredev 5 latest:

```
./bin/plone-compile-resources -C
[... SNIP ...]
2016-04-04 21:00:27 WARNING Init Class plone.app.drafts.storage.Storage has a security declaration for nonexistent method 'drafts'
Using site id: Plone
Target compile path: fetch from bundles
"bda_aaf_site" bundles compiles paths/filename
- css path: /home/workspacejensens/bda.aaf.site/src/bda/aaf/site/resources
- css name: aaf.css
- js path:  /home/workspacejensens/bda.aaf.site/src/bda/aaf/site/resources
- js name:  aaf-compiled.js
"layouts-editor" bundles compiles paths/filename
- css path: /home/workspacejensens/bda.aaf.site/devsrc/plone.app.mosaic/src/plone/app/mosaic/browser/static
- css name: layouts-editor.css
- js path:  /home/workspacejensens/bda.aaf.site/devsrc/plone.app.mosaic/src/plone/app/mosaic/browser/static
- js name:  layouts-editor.js
"mosaic" bundles compiles paths/filename
- css path: /home/workspacejensens/bda.aaf.site/devsrc/plone.app.mosaic/src/plone/app/mosaic/browser/static
- css name: plone-mosaic.css
- js path:  /home/workspacejensens/bda.aaf.site/devsrc/plone.app.mosaic/src/plone/app/mosaic/browser/static
- js name:  plone-mosaic.js
"plone-legacy" bundles compiles paths/filename
- css path: /home/workspacejensens/bda.aaf.site/devsrc/Products.CMFPlone/Products/CMFPlone/static
- css name: plone-legacy-compiled.css
- js path:  /home/workspacejensens/bda.aaf.site/devsrc/Products.CMFPlone/Products/CMFPlone/static
- js name:  plone-legacy-compiled.js
"plone-logged-in" bundles compiles paths/filename
- css path: /home/workspacejensens/bda.aaf.site/src/bda/aaf/site/resources
- css name: plone-logged-in-compiled.css
- js path:  /home/workspacejensens/bda.aaf.site/src/bda/aaf/site/resources
- js name:  plone-logged-in-compiled.min.js
"plone" bundles compiles paths/filename
- css path: /home/workspacejensens/bda.aaf.site/src/bda/aaf/site/resources
- css name: plone-compiled.css
- js path:  /home/workspacejensens/bda.aaf.site/src/bda/aaf/site/resources
- js name:  plone-compiled.min.js
"plone_app_imagecropping" bundles compiles paths/filename
- css path: /home/workspacejensens/bda.aaf.site/devsrc/plone.app.imagecropping/src/plone/app/imagecropping/browser/static
- css name: imagecropping.css
- js path:  /home/workspacejensens/bda.aaf.site/devsrc/plone.app.imagecropping/src/plone/app/imagecropping/browser/static
- js name:  imagecropping-compiled.js
"resourceregistry" bundles compiles paths/filename
- css path: /home/workspacejensens/bda.aaf.site/devsrc/Products.CMFPlone/Products/CMFPlone/static
- css name: resourceregistry-compiled.css
- js path:  /home/workspacejensens/bda.aaf.site/devsrc/Products.CMFPlone/Products/CMFPlone/static
- js name:  resourceregistry-compiled.min.js
"thememapper" bundles compiles paths/filename
- css path: /home/jensens/.buildout/shared-eggs/plone.app.theming-1.2.19-py2.7.egg/plone/app/theming/browser/resources
- css name: thememapper-compiled.css
- js path:  /home/jensens/.buildout/shared-eggs/plone.app.theming-1.2.19-py2.7.egg/plone/app/theming/browser/resources
- js name:  thememapper-compiled.min.js
"webcouturier.dropdownmenu" bundles compiles paths/filename
- css path: /home/workspacejensens/bda.aaf.site/devsrc/webcouturier.dropdownmenu/src/webcouturier/dropdownmenu/browser/static
- css name: webcouturier.dropdownmenu-compiled.css
Grunfile generated.
Setup npm env
Running command: npm install
Done.
```

and 

```
$ ./bin/plone-compile-resources -GIb webcouturier.dropdownmenu
Compile webcouturier.dropdownmenu
Running command: /usr/local/bin/grunt --gruntfile=/home/workspacejensens/bda.aaf.site/Gruntfile.js compile-webcouturier.dropdownmenu
Running "less:webcouturier.dropdownmenu" (less) task
>> 1 stylesheet created.
>> 1 sourcemap created.

Running "sed:sed252" (sed) task
[... SNIP ...]

Running "sed:sed287" (sed) task

Done, without errors.
Done.
```
